buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Fix for isar_flutter_libs namespace issue
subprojects {
    afterEvaluate { project ->
        if (project.name == 'isar_flutter_libs') {
            project.android {
                namespace 'com.isar.flutter.libs'
            }
        }
    }
}
